-- Disable RLS for demo environment to allow seamless cloud storage without Supabase Auth
ALTER TABLE public.billing_audit_logs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on billing_audit_logs" ON public.billing_audit_logs;
CREATE POLICY "Allow public all on billing_audit_logs" ON public.billing_audit_logs FOR ALL USING (true);
ALTER TABLE public.billing_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_clients DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on billing_clients" ON public.billing_clients;
CREATE POLICY "Allow public all on billing_clients" ON public.billing_clients FOR ALL USING (true);
ALTER TABLE public.billing_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_settings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on billing_settings" ON public.billing_settings;
CREATE POLICY "Allow public all on billing_settings" ON public.billing_settings FOR ALL USING (true);
ALTER TABLE public.billing_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_entities DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on business_entities" ON public.business_entities;
CREATE POLICY "Allow public all on business_entities" ON public.business_entities FOR ALL USING (true);
ALTER TABLE public.business_entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_service_rates DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on client_service_rates" ON public.client_service_rates;
CREATE POLICY "Allow public all on client_service_rates" ON public.client_service_rates FOR ALL USING (true);
ALTER TABLE public.client_service_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dps_accounts DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on dps_accounts" ON public.dps_accounts;
CREATE POLICY "Allow public all on dps_accounts" ON public.dps_accounts FOR ALL USING (true);
ALTER TABLE public.dps_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dps_installments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on dps_installments" ON public.dps_installments;
CREATE POLICY "Allow public all on dps_installments" ON public.dps_installments FOR ALL USING (true);
ALTER TABLE public.dps_installments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entity_bank_accounts DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on entity_bank_accounts" ON public.entity_bank_accounts;
CREATE POLICY "Allow public all on entity_bank_accounts" ON public.entity_bank_accounts FOR ALL USING (true);
ALTER TABLE public.entity_bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on expenses" ON public.expenses;
CREATE POLICY "Allow public all on expenses" ON public.expenses FOR ALL USING (true);
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fdr_accounts DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on fdr_accounts" ON public.fdr_accounts;
CREATE POLICY "Allow public all on fdr_accounts" ON public.fdr_accounts FOR ALL USING (true);
ALTER TABLE public.fdr_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_audit_logs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on financial_audit_logs" ON public.financial_audit_logs;
CREATE POLICY "Allow public all on financial_audit_logs" ON public.financial_audit_logs FOR ALL USING (true);
ALTER TABLE public.financial_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_reconciliations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on financial_reconciliations" ON public.financial_reconciliations;
CREATE POLICY "Allow public all on financial_reconciliations" ON public.financial_reconciliations FOR ALL USING (true);
ALTER TABLE public.financial_reconciliations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.input_vat_entries DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on input_vat_entries" ON public.input_vat_entries;
CREATE POLICY "Allow public all on input_vat_entries" ON public.input_vat_entries FOR ALL USING (true);
ALTER TABLE public.input_vat_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_email_logs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on invoice_email_logs" ON public.invoice_email_logs;
CREATE POLICY "Allow public all on invoice_email_logs" ON public.invoice_email_logs FOR ALL USING (true);
ALTER TABLE public.invoice_email_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on invoice_items" ON public.invoice_items;
CREATE POLICY "Allow public all on invoice_items" ON public.invoice_items FOR ALL USING (true);
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_payments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on invoice_payments" ON public.invoice_payments;
CREATE POLICY "Allow public all on invoice_payments" ON public.invoice_payments FOR ALL USING (true);
ALTER TABLE public.invoice_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_sequences DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on invoice_sequences" ON public.invoice_sequences;
CREATE POLICY "Allow public all on invoice_sequences" ON public.invoice_sequences FOR ALL USING (true);
ALTER TABLE public.invoice_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_snapshots DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on invoice_snapshots" ON public.invoice_snapshots;
CREATE POLICY "Allow public all on invoice_snapshots" ON public.invoice_snapshots FOR ALL USING (true);
ALTER TABLE public.invoice_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on invoices" ON public.invoices;
CREATE POLICY "Allow public all on invoices" ON public.invoices FOR ALL USING (true);
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.money_receipts DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on money_receipts" ON public.money_receipts;
CREATE POLICY "Allow public all on money_receipts" ON public.money_receipts FOR ALL USING (true);
ALTER TABLE public.money_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on profiles" ON public.profiles;
CREATE POLICY "Allow public all on profiles" ON public.profiles FOR ALL USING (true);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reserve_ledger DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on reserve_ledger" ON public.reserve_ledger;
CREATE POLICY "Allow public all on reserve_ledger" ON public.reserve_ledger FOR ALL USING (true);
ALTER TABLE public.reserve_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reserve_settings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on reserve_settings" ON public.reserve_settings;
CREATE POLICY "Allow public all on reserve_settings" ON public.reserve_settings FOR ALL USING (true);
ALTER TABLE public.reserve_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reserve_settings_history DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on reserve_settings_history" ON public.reserve_settings_history;
CREATE POLICY "Allow public all on reserve_settings_history" ON public.reserve_settings_history FOR ALL USING (true);
ALTER TABLE public.reserve_settings_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reserve_withdrawal_requests DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on reserve_withdrawal_requests" ON public.reserve_withdrawal_requests;
CREATE POLICY "Allow public all on reserve_withdrawal_requests" ON public.reserve_withdrawal_requests FOR ALL USING (true);
ALTER TABLE public.reserve_withdrawal_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.savings_documents DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on savings_documents" ON public.savings_documents;
CREATE POLICY "Allow public all on savings_documents" ON public.savings_documents FOR ALL USING (true);
ALTER TABLE public.savings_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_notifications DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on system_notifications" ON public.system_notifications;
CREATE POLICY "Allow public all on system_notifications" ON public.system_notifications FOR ALL USING (true);
ALTER TABLE public.system_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_audit_logs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on tax_audit_logs" ON public.tax_audit_logs;
CREATE POLICY "Allow public all on tax_audit_logs" ON public.tax_audit_logs FOR ALL USING (true);
ALTER TABLE public.tax_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_configurations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on tax_configurations" ON public.tax_configurations;
CREATE POLICY "Allow public all on tax_configurations" ON public.tax_configurations FOR ALL USING (true);
ALTER TABLE public.tax_configurations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vat_audit_logs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on vat_audit_logs" ON public.vat_audit_logs;
CREATE POLICY "Allow public all on vat_audit_logs" ON public.vat_audit_logs FOR ALL USING (true);
ALTER TABLE public.vat_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vat_configurations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on vat_configurations" ON public.vat_configurations;
CREATE POLICY "Allow public all on vat_configurations" ON public.vat_configurations FOR ALL USING (true);
ALTER TABLE public.vat_configurations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vat_documents DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on vat_documents" ON public.vat_documents;
CREATE POLICY "Allow public all on vat_documents" ON public.vat_documents FOR ALL USING (true);
ALTER TABLE public.vat_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vat_registration_profiles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on vat_registration_profiles" ON public.vat_registration_profiles;
CREATE POLICY "Allow public all on vat_registration_profiles" ON public.vat_registration_profiles FOR ALL USING (true);
ALTER TABLE public.vat_registration_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vat_returns DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on vat_returns" ON public.vat_returns;
CREATE POLICY "Allow public all on vat_returns" ON public.vat_returns FOR ALL USING (true);
ALTER TABLE public.vat_returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vat_service_categories DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public all on vat_service_categories" ON public.vat_service_categories;
CREATE POLICY "Allow public all on vat_service_categories" ON public.vat_service_categories FOR ALL USING (true);
ALTER TABLE public.vat_service_categories ENABLE ROW LEVEL SECURITY;
NOTIFY pgrst, 'reload schema';
