export const worldCountries = [
  // NORTH AMERICA (23)
  { city: "St. John's", country: "Antigua and Barbuda", flag: "ag", tz: "America/Antigua" },
  { city: "Nassau", country: "Bahamas", flag: "bs", tz: "America/Nassau" },
  { city: "Bridgetown", country: "Barbados", flag: "bb", tz: "America/Barbados" },
  { city: "Belmopan", country: "Belize", flag: "bz", tz: "America/Belize" },
  { city: "Ottawa", country: "Canada", flag: "ca", tz: "America/Toronto" },
  { city: "San José", country: "Costa Rica", flag: "cr", tz: "America/Costa_Rica" },
  { city: "Havana", country: "Cuba", flag: "cu", tz: "America/Havana" },
  { city: "Roseau", country: "Dominica", flag: "dm", tz: "America/Dominica" },
  { city: "Santo Domingo", country: "Dominican Republic", flag: "do", tz: "America/Santo_Domingo" },
  { city: "San Salvador", country: "El Salvador", flag: "sv", tz: "America/El_Salvador" },
  { city: "St. George's", country: "Grenada", flag: "gd", tz: "America/Grenada" },
  { city: "Guatemala City", country: "Guatemala", flag: "gt", tz: "America/Guatemala" },
  { city: "Port-au-Prince", country: "Haiti", flag: "ht", tz: "America/Port-au-Prince" },
  { city: "Tegucigalpa", country: "Honduras", flag: "hn", tz: "America/Tegucigalpa" },
  { city: "Kingston", country: "Jamaica", flag: "jm", tz: "America/Jamaica" },
  { city: "Mexico City", country: "Mexico", flag: "mx", tz: "America/Mexico_City" },
  { city: "Managua", country: "Nicaragua", flag: "ni", tz: "America/Managua" },
  { city: "Panama City", country: "Panama", flag: "pa", tz: "America/Panama" },
  { city: "Basseterre", country: "Saint Kitts and Nevis", flag: "kn", tz: "America/St_Kitts" },
  { city: "Castries", country: "Saint Lucia", flag: "lc", tz: "America/St_Lucia" },
  { city: "Kingstown", country: "Saint Vincent and the Grenadines", flag: "vc", tz: "America/St_Vincent" },
  { city: "Port of Spain", country: "Trinidad and Tobago", flag: "tt", tz: "America/Port_of_Spain" },
  { city: "Washington, D.C.", country: "United States", flag: "us", tz: "America/New_York" },

  // SOUTH AMERICA (12)
  { city: "Buenos Aires", country: "Argentina", flag: "ar", tz: "America/Argentina/Buenos_Aires" },
  { city: "Sucre", country: "Bolivia", flag: "bo", tz: "America/La_Paz" },
  { city: "Brasília", country: "Brazil", flag: "br", tz: "America/Sao_Paulo" },
  { city: "Santiago", country: "Chile", flag: "cl", tz: "America/Santiago" },
  { city: "Bogotá", country: "Colombia", flag: "co", tz: "America/Bogota" },
  { city: "Quito", country: "Ecuador", flag: "ec", tz: "America/Guayaquil" },
  { city: "Georgetown", country: "Guyana", flag: "gy", tz: "America/Guyana" },
  { city: "Asunción", country: "Paraguay", flag: "py", tz: "America/Asuncion" },
  { city: "Lima", country: "Peru", flag: "pe", tz: "America/Lima" },
  { city: "Paramaribo", country: "Suriname", flag: "sr", tz: "America/Paramaribo" },
  { city: "Montevideo", country: "Uruguay", flag: "uy", tz: "America/Montevideo" },
  { city: "Caracas", country: "Venezuela", flag: "ve", tz: "America/Caracas" },

  // EUROPE (43)
  { city: "Tirana", country: "Albania", flag: "al", tz: "Europe/Tirane" },
  { city: "Andorra la Vella", country: "Andorra", flag: "ad", tz: "Europe/Andorra" },
  { city: "Vienna", country: "Austria", flag: "at", tz: "Europe/Vienna" },
  { city: "Minsk", country: "Belarus", flag: "by", tz: "Europe/Minsk" },
  { city: "Brussels", country: "Belgium", flag: "be", tz: "Europe/Brussels" },
  { city: "Sarajevo", country: "Bosnia and Herzegovina", flag: "ba", tz: "Europe/Sarajevo" },
  { city: "Sofia", country: "Bulgaria", flag: "bg", tz: "Europe/Sofia" },
  { city: "Zagreb", country: "Croatia", flag: "hr", tz: "Europe/Zagreb" },
  { city: "Prague", country: "Czech Republic", flag: "cz", tz: "Europe/Prague" },
  { city: "Copenhagen", country: "Denmark", flag: "dk", tz: "Europe/Copenhagen" },
  { city: "Tallinn", country: "Estonia", flag: "ee", tz: "Europe/Tallinn" },
  { city: "Helsinki", country: "Finland", flag: "fi", tz: "Europe/Helsinki" },
  { city: "Paris", country: "France", flag: "fr", tz: "Europe/Paris" },
  { city: "Berlin", country: "Germany", flag: "de", tz: "Europe/Berlin" },
  { city: "Athens", country: "Greece", flag: "gr", tz: "Europe/Athens" },
  { city: "Budapest", country: "Hungary", flag: "hu", tz: "Europe/Budapest" },
  { city: "Reykjavík", country: "Iceland", flag: "is", tz: "Atlantic/Reykjavik" },
  { city: "Dublin", country: "Ireland", flag: "ie", tz: "Europe/Dublin" },
  { city: "Rome", country: "Italy", flag: "it", tz: "Europe/Rome" },
  { city: "Riga", country: "Latvia", flag: "lv", tz: "Europe/Riga" },
  { city: "Vaduz", country: "Liechtenstein", flag: "li", tz: "Europe/Vaduz" },
  { city: "Vilnius", country: "Lithuania", flag: "lt", tz: "Europe/Vilnius" },
  { city: "Luxembourg", country: "Luxembourg", flag: "lu", tz: "Europe/Luxembourg" },
  { city: "Valletta", country: "Malta", flag: "mt", tz: "Europe/Malta" },
  { city: "Chișinău", country: "Moldova", flag: "md", tz: "Europe/Chisinau" },
  { city: "Monaco", country: "Monaco", flag: "mc", tz: "Europe/Monaco" },
  { city: "Podgorica", country: "Montenegro", flag: "me", tz: "Europe/Podgorica" },
  { city: "Amsterdam", country: "Netherlands", flag: "nl", tz: "Europe/Amsterdam" },
  { city: "Skopje", country: "North Macedonia", flag: "mk", tz: "Europe/Skopje" },
  { city: "Oslo", country: "Norway", flag: "no", tz: "Europe/Oslo" },
  { city: "Warsaw", country: "Poland", flag: "pl", tz: "Europe/Warsaw" },
  { city: "Lisbon", country: "Portugal", flag: "pt", tz: "Europe/Lisbon" },
  { city: "Bucharest", country: "Romania", flag: "ro", tz: "Europe/Bucharest" },
  { city: "Moscow", country: "Russia", flag: "ru", tz: "Europe/Moscow" },
  { city: "San Marino", country: "San Marino", flag: "sm", tz: "Europe/San_Marino" },
  { city: "Belgrade", country: "Serbia", flag: "rs", tz: "Europe/Belgrade" },
  { city: "Bratislava", country: "Slovakia", flag: "sk", tz: "Europe/Bratislava" },
  { city: "Ljubljana", country: "Slovenia", flag: "si", tz: "Europe/Ljubljana" },
  { city: "Madrid", country: "Spain", flag: "es", tz: "Europe/Madrid" },
  { city: "Stockholm", country: "Sweden", flag: "se", tz: "Europe/Stockholm" },
  { city: "Bern", country: "Switzerland", flag: "ch", tz: "Europe/Zurich" },
  { city: "Kyiv", country: "Ukraine", flag: "ua", tz: "Europe/Kiev" },
  { city: "London", country: "United Kingdom", flag: "gb", tz: "Europe/London" },

  // ASIA (47)
  { city: "Kabul", country: "Afghanistan", flag: "af", tz: "Asia/Kabul" },
  { city: "Yerevan", country: "Armenia", flag: "am", tz: "Asia/Yerevan" },
  { city: "Baku", country: "Azerbaijan", flag: "az", tz: "Asia/Baku" },
  { city: "Manama", country: "Bahrain", flag: "bh", tz: "Asia/Bahrain" },
  { city: "Dhaka", country: "Bangladesh", flag: "bd", tz: "Asia/Dhaka" },
  { city: "Thimphu", country: "Bhutan", flag: "bt", tz: "Asia/Thimphu" },
  { city: "Bandar Seri Begawan", country: "Brunei", flag: "bn", tz: "Asia/Brunei" },
  { city: "Phnom Penh", country: "Cambodia", flag: "kh", tz: "Asia/Phnom_Penh" },
  { city: "Beijing", country: "China", flag: "cn", tz: "Asia/Shanghai" },
  { city: "Nicosia", country: "Cyprus", flag: "cy", tz: "Asia/Nicosia" },
  { city: "Tbilisi", country: "Georgia", flag: "ge", tz: "Asia/Tbilisi" },
  { city: "New Delhi", country: "India", flag: "in", tz: "Asia/Kolkata" },
  { city: "Jakarta", country: "Indonesia", flag: "id", tz: "Asia/Jakarta" },
  { city: "Tehran", country: "Iran", flag: "ir", tz: "Asia/Tehran" },
  { city: "Baghdad", country: "Iraq", flag: "iq", tz: "Asia/Baghdad" },
  { city: "Jerusalem", country: "Israel", flag: "il", tz: "Asia/Jerusalem" },
  { city: "Tokyo", country: "Japan", flag: "jp", tz: "Asia/Tokyo" },
  { city: "Amman", country: "Jordan", flag: "jo", tz: "Asia/Amman" },
  { city: "Astana", country: "Kazakhstan", flag: "kz", tz: "Asia/Almaty" },
  { city: "Kuwait City", country: "Kuwait", flag: "kw", tz: "Asia/Kuwait" },
  { city: "Bishkek", country: "Kyrgyzstan", flag: "kg", tz: "Asia/Bishkek" },
  { city: "Vientiane", country: "Laos", flag: "la", tz: "Asia/Vientiane" },
  { city: "Beirut", country: "Lebanon", flag: "lb", tz: "Asia/Beirut" },
  { city: "Kuala Lumpur", country: "Malaysia", flag: "my", tz: "Asia/Kuala_Lumpur" },
  { city: "Malé", country: "Maldives", flag: "mv", tz: "Indian/Maldives" },
  { city: "Ulaanbaatar", country: "Mongolia", flag: "mn", tz: "Asia/Ulaanbaatar" },
  { city: "Naypyidaw", country: "Myanmar", flag: "mm", tz: "Asia/Yangon" },
  { city: "Kathmandu", country: "Nepal", flag: "np", tz: "Asia/Kathmandu" },
  { city: "Pyongyang", country: "North Korea", flag: "kp", tz: "Asia/Pyongyang" },
  { city: "Muscat", country: "Oman", flag: "om", tz: "Asia/Muscat" },
  { city: "Islamabad", country: "Pakistan", flag: "pk", tz: "Asia/Karachi" },
  { city: "Manila", country: "Philippines", flag: "ph", tz: "Asia/Manila" },
  { city: "Doha", country: "Qatar", flag: "qa", tz: "Asia/Qatar" },
  { city: "Riyadh", country: "Saudi Arabia", flag: "sa", tz: "Asia/Riyadh" },
  { city: "Singapore", country: "Singapore", flag: "sg", tz: "Asia/Singapore" },
  { city: "Seoul", country: "South Korea", flag: "kr", tz: "Asia/Seoul" },
  { city: "Colombo", country: "Sri Lanka", flag: "lk", tz: "Asia/Colombo" },
  { city: "Damascus", country: "Syria", flag: "sy", tz: "Asia/Damascus" },
  { city: "Dushanbe", country: "Tajikistan", flag: "tj", tz: "Asia/Dushanbe" },
  { city: "Bangkok", country: "Thailand", flag: "th", tz: "Asia/Bangkok" },
  { city: "Dili", country: "Timor-Leste", flag: "tl", tz: "Asia/Dili" },
  { city: "Ankara", country: "Turkey", flag: "tr", tz: "Europe/Istanbul" },
  { city: "Ashgabat", country: "Turkmenistan", flag: "tm", tz: "Asia/Ashgabat" },
  { city: "Abu Dhabi", country: "United Arab Emirates", flag: "ae", tz: "Asia/Dubai" },
  { city: "Tashkent", country: "Uzbekistan", flag: "uz", tz: "Asia/Tashkent" },
  { city: "Hanoi", country: "Vietnam", flag: "vn", tz: "Asia/Ho_Chi_Minh" },
  { city: "Sana'a", country: "Yemen", flag: "ye", tz: "Asia/Aden" },

  // AFRICA (54)
  { city: "Algiers", country: "Algeria", flag: "dz", tz: "Africa/Algiers" },
  { city: "Luanda", country: "Angola", flag: "ao", tz: "Africa/Luanda" },
  { city: "Porto-Novo", country: "Benin", flag: "bj", tz: "Africa/Porto-Novo" },
  { city: "Gaborone", country: "Botswana", flag: "bw", tz: "Africa/Gaborone" },
  { city: "Ouagadougou", country: "Burkina Faso", flag: "bf", tz: "Africa/Ouagadougou" },
  { city: "Gitega", country: "Burundi", flag: "bi", tz: "Africa/Bujumbura" },
  { city: "Praia", country: "Cabo Verde", flag: "cv", tz: "Atlantic/Cape_Verde" },
  { city: "Yaoundé", country: "Cameroon", flag: "cm", tz: "Africa/Douala" },
  { city: "Bangui", country: "Central African Republic", flag: "cf", tz: "Africa/Bangui" },
  { city: "N'Djamena", country: "Chad", flag: "td", tz: "Africa/Ndjamena" },
  { city: "Moroni", country: "Comoros", flag: "km", tz: "Indian/Comoro" },
  { city: "Kinshasa", country: "Democratic Republic of the Congo", flag: "cd", tz: "Africa/Kinshasa" },
  { city: "Brazzaville", country: "Republic of the Congo", flag: "cg", tz: "Africa/Brazzaville" },
  { city: "Yamoussoukro", country: "Côte d'Ivoire", flag: "ci", tz: "Africa/Abidjan" },
  { city: "Djibouti", country: "Djibouti", flag: "dj", tz: "Africa/Djibouti" },
  { city: "Cairo", country: "Egypt", flag: "eg", tz: "Africa/Cairo" },
  { city: "Malabo", country: "Equatorial Guinea", flag: "gq", tz: "Africa/Malabo" },
  { city: "Asmara", country: "Eritrea", flag: "er", tz: "Africa/Asmara" },
  { city: "Mbabane", country: "Eswatini", flag: "sz", tz: "Africa/Mbabane" },
  { city: "Addis Ababa", country: "Ethiopia", flag: "et", tz: "Africa/Addis_Ababa" },
  { city: "Libreville", country: "Gabon", flag: "ga", tz: "Africa/Libreville" },
  { city: "Banjul", country: "Gambia", flag: "gm", tz: "Africa/Banjul" },
  { city: "Accra", country: "Ghana", flag: "gh", tz: "Africa/Accra" },
  { city: "Conakry", country: "Guinea", flag: "gn", tz: "Africa/Conakry" },
  { city: "Bissau", country: "Guinea-Bissau", flag: "gw", tz: "Africa/Bissau" },
  { city: "Nairobi", country: "Kenya", flag: "ke", tz: "Africa/Nairobi" },
  { city: "Maseru", country: "Lesotho", flag: "ls", tz: "Africa/Maseru" },
  { city: "Monrovia", country: "Liberia", flag: "lr", tz: "Africa/Monrovia" },
  { city: "Tripoli", country: "Libya", flag: "ly", tz: "Africa/Tripoli" },
  { city: "Antananarivo", country: "Madagascar", flag: "mg", tz: "Indian/Antananarivo" },
  { city: "Lilongwe", country: "Malawi", flag: "mw", tz: "Africa/Blantyre" },
  { city: "Bamako", country: "Mali", flag: "ml", tz: "Africa/Bamako" },
  { city: "Nouakchott", country: "Mauritania", flag: "mr", tz: "Africa/Nouakchott" },
  { city: "Port Louis", country: "Mauritius", flag: "mu", tz: "Indian/Mauritius" },
  { city: "Rabat", country: "Morocco", flag: "ma", tz: "Africa/Casablanca" },
  { city: "Maputo", country: "Mozambique", flag: "mz", tz: "Africa/Maputo" },
  { city: "Windhoek", country: "Namibia", flag: "na", tz: "Africa/Windhoek" },
  { city: "Niamey", country: "Niger", flag: "ne", tz: "Africa/Niamey" },
  { city: "Abuja", country: "Nigeria", flag: "ng", tz: "Africa/Lagos" },
  { city: "Kigali", country: "Rwanda", flag: "rw", tz: "Africa/Kigali" },
  { city: "São Tomé", country: "São Tomé and Príncipe", flag: "st", tz: "Africa/Sao_Tome" },
  { city: "Dakar", country: "Senegal", flag: "sn", tz: "Africa/Dakar" },
  { city: "Victoria", country: "Seychelles", flag: "sc", tz: "Indian/Mahe" },
  { city: "Freetown", country: "Sierra Leone", flag: "sl", tz: "Africa/Freetown" },
  { city: "Mogadishu", country: "Somalia", flag: "so", tz: "Africa/Mogadishu" },
  { city: "Pretoria", country: "South Africa", flag: "za", tz: "Africa/Johannesburg" },
  { city: "Juba", country: "South Sudan", flag: "ss", tz: "Africa/Juba" },
  { city: "Khartoum", country: "Sudan", flag: "sd", tz: "Africa/Khartoum" },
  { city: "Dodoma", country: "Tanzania", flag: "tz", tz: "Africa/Dar_es_Salaam" },
  { city: "Lomé", country: "Togo", flag: "tg", tz: "Africa/Lome" },
  { city: "Tunis", country: "Tunisia", flag: "tn", tz: "Africa/Tunis" },
  { city: "Kampala", country: "Uganda", flag: "ug", tz: "Africa/Kampala" },
  { city: "Lusaka", country: "Zambia", flag: "zm", tz: "Africa/Lusaka" },
  { city: "Harare", country: "Zimbabwe", flag: "zw", tz: "Africa/Harare" },

  // OCEANIA (14)
  { city: "Canberra", country: "Australia", flag: "au", tz: "Australia/Sydney" },
  { city: "Suva", country: "Fiji", flag: "fj", tz: "Pacific/Fiji" },
  { city: "Tarawa", country: "Kiribati", flag: "ki", tz: "Pacific/Tarawa" },
  { city: "Majuro", country: "Marshall Islands", flag: "mh", tz: "Pacific/Majuro" },
  { city: "Palikir", country: "Micronesia", flag: "fm", tz: "Pacific/Pohnpei" },
  { city: "Yaren", country: "Nauru", flag: "nr", tz: "Pacific/Nauru" },
  { city: "Wellington", country: "New Zealand", flag: "nz", tz: "Pacific/Auckland" },
  { city: "Ngerulmud", country: "Palau", flag: "pw", tz: "Pacific/Palau" },
  { city: "Port Moresby", country: "Papua New Guinea", flag: "pg", tz: "Pacific/Port_Moresby" },
  { city: "Apia", country: "Samoa", flag: "ws", tz: "Pacific/Apia" },
  { city: "Honiara", country: "Solomon Islands", flag: "sb", tz: "Pacific/Guadalcanal" },
  { city: "Nukuʻalofa", country: "Tonga", flag: "to", tz: "Pacific/Tongatapu" },
  { city: "Funafuti", country: "Tuvalu", flag: "tv", tz: "Pacific/Funafuti" },
  { city: "Port Vila", country: "Vanuatu", flag: "vu", tz: "Pacific/Efate" }
];

export const groupedCountries = {
  "North America": worldCountries.slice(0, 23),
  "South America": worldCountries.slice(23, 35),
  "Europe": worldCountries.slice(35, 78),
  "Asia": worldCountries.slice(78, 125),
  "Africa": worldCountries.slice(125, 179),
  "Oceania": worldCountries.slice(179, 193),
};
